services:
  products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  customerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

