services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=kiran@123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    restart: always

  products:
    image: ${DOCKER_REGISTRY-}products
    build:
      context: .
      dockerfile: Products/Dockerfile
    environment:
        DbServer: "sqlserver"
        DbPort: "1433"
        DbUser: "SA"
        Password: "kiran@123"
        Database: "ProductsDB"
    ports:
        - "3002:80"
    depends_on:
          - sqlserver
  front-end:
    image: ${DOCKER_REGISTRY-}front-end
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - products
